site:
  name: OceanExpress
  site: 'https://oceanexpresscr.vercel.app'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: OceanExpressCR
    template: '%s — OceanExpress'
  description: "\U0001F680 Logistic solutions for your business."
  robots:
    index: true
    follow: true
  openGraph:
    title: OceanExpressCR
    type: website
    description: Logistic solutions for your business
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628

i18n:
  language: es
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only"

  tokens:
    default:
      fonts:
        sans: InterVariable
        serif: var(--ph-font-sans)
        heading: var(--ph-font-sans)
      colors:
        default: rgb(16 16 16)
        heading: rgb(0 0 0)
        muted: rgb(40 40 40)
        bgPage: rgb(255 255 255)
        primary: rgb(0 124 220)
        secondary: rgb(30 58 138)
        accent: rgb(109 40 217)
        info: rgb(119 182 234)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)
